function doGet(e) {
/*
1) CREO IL SERVIZIO HTML
2) CREO LA PAGINA HTML 
3) NELLA PG HTML CREO UN BOTTONE CON ID
4) POI CREO LO SCRIPT E UN EVENTLISTENER
5) NELL'EVENTLISTENER CREO LA FUNZIONE 
6) CREO LA FUNZIONE N°1 COLLEGATA ALL'EVENT LISTNER NELLA PAGINA HTML
7) COLLEGO LA FUNZIONE N° 1 ALLA FUNZIONE N°2 IN BACKEND
8) CREO IN PAGE.HTML UN INPUT BOX
*/
  return HtmlService.createHtmlOutputFromFile("page");
  
 
}

// FUNZIONE N°2
 function userClicked (name) {
  Logger.log(name +"Qualcuno ha cliccato!");
  
  }